"""Precomputed seven-day forecast research results for the Streamlit dashboard.

This page never imports training functions and never fits a model. It reads the
stable artifacts generated by ``python main.py train-models``.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

ARTIFACT_ROOT = PROJECT_ROOT / "output" / "forecasting"
METRICS_PATH = ARTIFACT_ROOT / "metrics" / "model_comparison_metrics.json"
PROMOTION_PATH = ARTIFACT_ROOT / "metrics" / "promotion_decision.json"
PROVENANCE_PATH = ARTIFACT_ROOT / "audits" / "dataset_provenance.json"
HOLDOUT_PATH = ARTIFACT_ROOT / "predictions" / "final_holdout_predictions.csv"
FOLDS_PATH = ARTIFACT_ROOT / "metrics" / "fold_metrics.csv"
IMPORTANCE_PATH = ARTIFACT_ROOT / "diagnostics" / "oof_permutation_importance.csv"
REGIME_PATH = ARTIFACT_ROOT / "diagnostics" / "error_by_regime.csv"
REGISTRY_PATH = ARTIFACT_ROOT / "models" / "model_registry.json"
LEAKAGE_PATH = ARTIFACT_ROOT / "audits" / "leakage_audit.json"
MONITORING_PATH = ARTIFACT_ROOT / "monitoring" / "monitoring_summary.json"

NAVY = "#163B65"
SLATE = "#3F5063"
BLUE = "#2E75B6"
AMBER = "#D97706"
GREEN = "#238636"
RED = "#B42318"


st.set_page_config(
    page_title="Forecast Research | HHS UAC Analytics",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)


def apply_styles() -> None:
    """Apply the dashboard's slate/navy visual language."""

    st.markdown(
        f"""
        <style>
        .stApp {{background:#F5F7FA;color:#172033}}
        [data-testid="stSidebar"] {{background:#EDF2F7;border-right:1px solid #D9E1EA}}
        .forecast-header {{background:linear-gradient(110deg,#172033,{NAVY});color:white;
            border-radius:10px;padding:1.3rem 1.5rem;margin-bottom:1rem}}
        .forecast-header h1 {{color:white;margin:0 0 .35rem}}
        .forecast-header p {{color:#DCE7F2;margin:0}}
        .research-warning {{background:#FFF8E6;border:1px solid #EDC46B;
            border-left:5px solid {AMBER};border-radius:7px;padding:.8rem 1rem}}
        div[data-testid="stMetric"] {{background:white;border:1px solid #D9E1EA;
            border-left:4px solid {BLUE};border-radius:8px;padding:.85rem}}
        </style>
        """,
        unsafe_allow_html=True,
    )


@st.cache_data(show_spinner=False)
def load_forecast_artifacts() -> dict[str, Any]:
    """Load and minimally validate precomputed JSON/CSV forecast artifacts."""

    required = (
        METRICS_PATH,
        PROMOTION_PATH,
        PROVENANCE_PATH,
        HOLDOUT_PATH,
        FOLDS_PATH,
        IMPORTANCE_PATH,
        REGIME_PATH,
        REGISTRY_PATH,
        LEAKAGE_PATH,
    )
    missing = [path for path in required if not path.is_file()]
    if missing:
        raise FileNotFoundError(
            "Missing forecast artifact(s): " + ", ".join(path.name for path in missing)
        )
    metrics = json.loads(METRICS_PATH.read_text(encoding="utf-8"))
    promotion = json.loads(PROMOTION_PATH.read_text(encoding="utf-8"))
    provenance = json.loads(PROVENANCE_PATH.read_text(encoding="utf-8"))
    predictions = pd.read_csv(
        HOLDOUT_PATH,
        parse_dates=["forecast_origin_date", "target_date"],
    )
    folds = pd.read_csv(FOLDS_PATH)
    importance = pd.read_csv(IMPORTANCE_PATH)
    regimes = pd.read_csv(REGIME_PATH)
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    leakage = json.loads(LEAKAGE_PATH.read_text(encoding="utf-8"))
    monitoring = (
        json.loads(MONITORING_PATH.read_text(encoding="utf-8"))
        if MONITORING_PATH.is_file()
        else None
    )
    expected = {
        "target_date",
        "actual_value",
        "model_name",
        "reconstructed_absolute_prediction",
        "lower_interval",
        "upper_interval",
    }
    if predictions.empty or not expected.issubset(predictions.columns):
        raise ValueError("Holdout prediction artifact has an invalid schema.")
    return {
        "metrics": metrics,
        "promotion": promotion,
        "provenance": provenance,
        "predictions": predictions,
        "folds": folds,
        "importance": importance,
        "regimes": regimes,
        "registry": registry,
        "leakage": leakage,
        "monitoring": monitoring,
    }


def comparison_table(metrics: dict[str, Any]) -> pd.DataFrame:
    """Create a compact sorted model-comparison table."""

    rows = []
    for name, values in metrics.get("models", {}).items():
        validation = values["walk_forward"]
        holdout = values["holdout"]
        rows.append(
            {
                "Model": name.replace("_", " ").title(),
                "Walk-forward MAE": validation["mean_mae"],
                "CV standard deviation": validation["std_mae"],
                "Worst-fold MAE": validation["worst_fold_mae"],
                "Holdout MAE": holdout["mae"],
                "Holdout RMSE": holdout["rmse"],
                "Holdout MASE": holdout["mase_vs_persistence"],
                "Improvement vs persistence (%)": holdout["mae_improvement_vs_persistence_percent"],
            }
        )
    return pd.DataFrame(rows).sort_values("Walk-forward MAE").reset_index(drop=True)


def render_forecast_chart(predictions: pd.DataFrame, champion: str) -> None:
    """Render actual, champion, persistence, and calibrated intervals."""

    champion_rows = predictions.loc[predictions["model_name"] == champion].sort_values(
        "target_date"
    )
    persistence = predictions.loc[predictions["model_name"] == "persistence"].sort_values(
        "target_date"
    )
    figure = go.Figure()
    figure.add_trace(
        go.Scatter(
            x=champion_rows["target_date"],
            y=champion_rows["upper_interval"],
            mode="lines",
            line={"width": 0},
            showlegend=False,
            hoverinfo="skip",
        )
    )
    figure.add_trace(
        go.Scatter(
            x=champion_rows["target_date"],
            y=champion_rows["lower_interval"],
            mode="lines",
            line={"width": 0},
            fill="tonexty",
            fillcolor="rgba(46,117,182,.16)",
            name="LightGBM quantile 80% interval",
        )
    )
    figure.add_trace(
        go.Scatter(
            x=champion_rows["target_date"],
            y=champion_rows["actual_value"],
            mode="lines",
            name="Actual",
            line={"color": NAVY, "width": 2.5},
        )
    )
    figure.add_trace(
        go.Scatter(
            x=champion_rows["target_date"],
            y=champion_rows["median_prediction"],
            mode="lines",
            name="LightGBM quantile median",
            line={"color": BLUE, "dash": "dash"},
        )
    )
    figure.add_trace(
        go.Scatter(
            x=champion_rows["target_date"],
            y=champion_rows["reconstructed_absolute_prediction"],
            mode="lines",
            name=f"Champion: {champion.replace('_', ' ').title()}",
            line={"color": AMBER, "width": 2},
        )
    )
    if champion != "persistence":
        figure.add_trace(
            go.Scatter(
                x=persistence["target_date"],
                y=persistence["reconstructed_absolute_prediction"],
                mode="lines",
                name="Persistence",
                line={"color": SLATE, "dash": "dot"},
            )
        )
    figure.update_layout(
        title="Untouched Holdout: Actual versus Forecast",
        template="plotly_white",
        hovermode="x unified",
        height=500,
        legend={"orientation": "h", "y": 1.08},
        yaxis_title="Children under care",
    )
    st.plotly_chart(figure, width="stretch")


def main() -> None:
    """Render precomputed forecasting research results."""

    apply_styles()
    st.markdown(
        """
        <div class="forecast-header">
          <h1>Seven-Day Capacity Forecast Research</h1>
          <p>Leakage-safe statistical, linear, boosting, hybrid, and ensemble
          comparisons using walk-forward validation and a chronological holdout.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    try:
        artifacts = load_forecast_artifacts()
    except (FileNotFoundError, OSError, ValueError, json.JSONDecodeError) as exc:
        st.warning(f"Forecast results are unavailable: {exc}")
        st.code("python main.py train-models", language="bash")
        st.info("Training is intentionally never started during page rendering.")
        return

    metrics = artifacts["metrics"]
    promotion = artifacts["promotion"]
    provenance = artifacts["provenance"]
    predictions = artifacts["predictions"]
    registry = artifacts["registry"]
    leakage = artifacts["leakage"]
    monitoring = artifacts["monitoring"]
    champion = str(promotion["champion_model"])
    champion_metrics = metrics["models"][champion]

    st.markdown(
        f"""
        <div class="research-warning"><strong>Research output—not an official HHS
        or CBP forecast.</strong> {provenance["generalization_warning"]}</div>
        """,
        unsafe_allow_html=True,
    )
    st.caption(
        f"Provenance classification: {provenance['classification']} · "
        f"Processed coverage: {provenance['date_range']['start']} to "
        f"{provenance['date_range']['end']} · No child-level or personal data"
    )

    with st.expander("Reviewer summary and methodology", expanded=True):
        left, right = st.columns(2)
        with left:
            st.markdown(
                """
                **Research question.** Can a forecast selected only from
                development-period evidence improve seven-day aggregate care-load
                prediction over persistence?

                **Design.** The experiment predicts seven-day load change, uses five
                expanding-window folds with seven-day gaps, freezes every
                configuration and ensemble weight, then opens a 214-origin
                chronological holdout as a promotion gate.
                """
            )
        with right:
            audit_status = "Passed" if leakage["passed"] else "Failed"
            st.markdown(
                f"""
                - **Artifact version:** `{registry["registry_version"]}`
                - **Source hash:** `{registry["source_sha256"][:16]}…`
                - **Leakage audit:** {audit_status}
                - **Selection rule:** {promotion["selection_rule"]}
                """
            )

    status_color = GREEN if promotion["passed"] else AMBER
    columns = st.columns(5)
    columns[0].metric("Champion type", "Blend")
    columns[1].metric("Promotion gates", "Passed" if promotion["passed"] else "Failed")
    columns[2].metric("Champion CV MAE", f"{champion_metrics['walk_forward']['mean_mae']:,.2f}")
    columns[3].metric("Champion holdout MAE", f"{champion_metrics['holdout']['mae']:,.2f}")
    columns[4].metric("Holdout rows", f"{metrics['holdout']['rows']:,}")
    st.markdown(
        f"<div style='border-left:5px solid {status_color};padding:.65rem 1rem;"
        f"background:white'><strong>Decision:</strong> {promotion['rationale']}</div>",
        unsafe_allow_html=True,
    )

    if monitoring:
        st.caption(
            "Offline monitor · "
            f"status: {monitoring['model_status']} · "
            f"active model: {monitoring['active_model'].replace('_', ' ')} · "
            f"30-day MAE: {monitoring['metrics']['rolling_mae']:.2f} · "
            f"persistence MAE: {monitoring['metrics']['rolling_persistence_mae']:.2f} · "
            f"input drift flag: {monitoring['metrics']['input_drift_flag']}"
        )

    render_forecast_chart(predictions, champion)

    comparison_tab, folds_tab, importance_tab, regimes_tab, limitations_tab = st.tabs(
        [
            "Model Comparison",
            "Walk-Forward Folds",
            "Feature Importance",
            "Error by Regime",
            "Uncertainty & Limitations",
        ]
    )
    with comparison_tab:
        table = comparison_table(metrics)
        st.dataframe(table.style.format(precision=3), width="stretch", hide_index=True)
        chart = px.bar(
            table,
            x="Model",
            y=["Walk-forward MAE", "Holdout MAE"],
            barmode="group",
            color_discrete_sequence=[BLUE, AMBER],
            title="Development and Holdout MAE",
        )
        st.plotly_chart(chart, width="stretch")
    with folds_tab:
        fold_chart = px.line(
            artifacts["folds"],
            x="fold",
            y="mae",
            color="model_name",
            markers=True,
            title="Equal-Duration Walk-Forward Fold MAE",
        )
        fold_chart.update_layout(template="plotly_white", yaxis_title="MAE")
        st.plotly_chart(fold_chart, width="stretch")
        st.dataframe(artifacts["folds"], width="stretch", hide_index=True)
    with importance_tab:
        importance = artifacts["importance"].head(25)
        if importance.empty:
            st.info("Permutation importance is unavailable for this run.")
        else:
            figure = px.bar(
                importance.sort_values("mean_mae_increase"),
                x="mean_mae_increase",
                y="feature",
                orientation="h",
                title="Out-of-Fold Permutation Importance",
                color_discrete_sequence=[BLUE],
            )
            st.plotly_chart(figure, width="stretch")
            st.caption(
                "Correlated predictors can divide or mask permutation importance; "
                "interpret rankings as model diagnostics, not causal effects."
            )
    with regimes_tab:
        regimes = artifacts["regimes"]
        selected_dimension = st.selectbox(
            "Diagnostic dimension", sorted(regimes["dimension"].unique())
        )
        view = regimes.loc[regimes["dimension"] == selected_dimension]
        regime_chart = px.bar(
            view,
            x="regime",
            y="mae",
            color="rows",
            color_continuous_scale="Blues",
            title=f"Champion Error by {selected_dimension.replace('_', ' ').title()}",
        )
        st.plotly_chart(regime_chart, width="stretch")
        st.dataframe(view, width="stretch", hide_index=True)
    with limitations_tab:
        st.markdown(
            """
            **Uncertainty interpretation.** The displayed band comes from
            LightGBM quantile models calibrated using development evidence. Wide
            bands and unusually high holdout coverage indicate conservative
            uncertainty, not validated operational certainty.

            **Known limitations**

            - The source file has no recorded authoritative publisher URL,
              retrieval timestamp, license, or external signature.
            - 355 dates and 1,775 numeric values were imputed in preprocessing.
            - One aggregate series cannot represent facilities, geography,
              staffing, case complexity, policy shifts, or child-welfare outcomes.
            - Feature importance is predictive and conditional, never causal.
            - Forecasts are frozen research evaluations, not live predictions.
            """
        )

    st.divider()
    st.caption(
        "Forecasts support reproducible research only. They do not make decisions "
        "about individual children and must not be used as automated operational directives."
    )


if __name__ == "__main__":
    main()
